travis:
  secure:
    BINSTAR_TOKEN: hOF5E+7I0+EnWrKf3DHgz7GbzQ/3ASTqac+r/gN07rTrFxjJtljr6rYGsKbbS7Gdz1K7T4I/9g7D2F+4otqYqW1jP3lVFHwdiJyT2j+vNCCjkQ2OiSwaD3EBj31CTVe9zLRnj0kWPdBP1/n01KscEHZcM4GtYLqIQZ1FZWtwYq+evcgj5UQE9r6dk6TiSwT15tAKWAsokL85/9xHatHn/+W9OtZDRu0IpAw0YXA9pX/MrWB+JeGIa2VPqf4G37VXw7AR3kKc8fCmPfKDqDIx2UCOCs1Uccc5MeHMyzf1APyX5p21TbPqqRWbyPk0cnrunPnL1pH7kjpSCcQL4LGKuHqwDu12LPwsnvJ+3NnsV1PtaS1mu6Rbkif0qkKQPjGEX4Km7Xi+XMkfbGevUZlejhw33rwFYYiHCToau19C79lbm45lBi5Bf2/+VML0pCHRbnkhdPhxHQ6HRiy4856nvo+M+69zSo6ilqyxa9BE97xT7cqs6fs4PPBIvBopE/8jpDJY10HvNnmxw4e9n1UC67cOAcuz0saKJmmVve6kA7iyeW4ztiVYYjgw4GEEURruhiPmgC5MNJwPmkwE7kb7fZCgVYwiO3sRrElTXI7dqwpQYYldxNbT4Owh0ftNpG9ECRmYs+ZzcUpUziawGOyXrGOc8s2ZXQQgXVbTk9VrpWo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
