travis:
  secure:
    BINSTAR_TOKEN: yXQ+OeWAqzrqjuzgVjyOsqe9n8M8MW6qlkFZscOP0fdsBOCDKBPSdt1uvL9DPSzPIn3Li0bbTza52DaB+zK6uW8He8piOGkGN4Gp8QN1e9lhWNg4RRxGfwnHvDb1lyf63Sb3iWJWvpUCW+wzNiVZWvh69lp+2p53BO6bLEoEm9XboJ1hDBcxl0gggT03UAxYLR7rEOTMuH9qrbJzk+aciL3BJbgPoc3mSNoV0a/SzUOoBmVAk96UiCz5HrwK/ltaNZcO36aYVB3G4we8U5YIS59DFU1CfGS5SrdzRhxOUTUzCv2x1s9TRsZgZNiUKx/+hM86VGV/Xnj+qotCAzonBKz3PQTTEEHcoPj0HLZv5puSbdl/jKM+yu42Lxmhj5PGT59RaptAsV/PaM+Ppdr3Li+AIDU7EglIAzqMI60TuG1Moa5piyFzBRSSr0j5vlA/shQlbhovi3QLIZpd2j9cYFxiM0/UKZeE/wOcrymkNCb725hbY5gLoG0QIAx7CL48fJkmXTaPF1AyLaBVL0A0R0FA46TyD6xNEZ4NuXqK4R55BG7FuJqDXiDqk6PmNVS+w6hjjSsc3clMVRbJHOny3KmjigSOmIBgwwug3iSX/Ty9VmcAT2PmQtwqDLnQWMPNd8L2f6V3qbMzNVxizCH+tXI1FwR/H9jx5UZ+lX88+5U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
